### ISSUE TITLE
Use in new Kali 1.1.0

### ISSUE THREAD

**Issue by JudasRose** [P0cL4bs/3vilTwinAttacker#3]
Starts up with sudo ok.

Can not do DNS spoof or Driftnetthrough tools menu.

Error: "xterm: No absolute path for shell:DNS" when trying to run DNS spoof.
Error: "xterm: No absolute path for shell:Started" when trying to run Driftnet.

I also think there may be a problem with the SSL striping implementation. Trying to do this still brings up https sites. I also know it is not HSTS is not causing this.

**Comment by msfcd3r** [comment]
Thank you for Reported, I'll  fix the bug.  the problem not is with SSL, the bug is in args the xterm. -T not is permitted space.
wait next version the tool. v 0.5.3 with more modules. :D. thank's.
