### ISSUE TITLE
Enhancments 

### ISSUE THREAD

**Issue by Zaratros** [P0cL4bs/3vilTwinAttacker#4]
Hello !

I really like this tool and wish to see it developped further. I have some suggestions if you don't mind.
Can you add an option to do the followings please ?
-Create a captive portal the same way as Linset to get the network's password for example.
-Add a redirection option to redirect all trafic from htpp(s)://www.facebook.com for example to a certain ip the same way as LANs.py for example to harvest credentials.

I wish to see all the interesting tools assembled in a single tool.

**Comment by msfcd3r** [comment]
hi! great issue
l'll try develop a module with these functions in next update. 
thank's

**Comment by Zaratros** [comment]
Thank you ! Good luck.
