### ISSUE TITLE
Airbase-ng 

### ISSUE THREAD

**Issue by Zaratros** [P0cL4bs/3vilTwinAttacker#5]
Hello !
 I have another suggestion for you today. In this tutorial http://www.crack-wifi.com/forum/topic-10455-tuto-rogue-ap-discrete-en-full-wpa-avec-hostapd.html Aside from using mdk3 to jam the access point, they used airbase-ng too. They said that if coupled with mdk3 it makes the ap go to the bottom of the list in windows and make a red cross appear next to it. It might add a certain credibility to the attack as the client won't be able to see the old ap. and he wouldn't even be able to log in it as shown in this image http://zupimages.net/up/14/14/dv0h.bmp
Here are the commands used with it : http://zupimages.net/up/14/15/p291.png for mdk3
http://zupimages.net/up/14/15/dncc.png for airbase-ng

**Comment by msfcd3r** [comment]
thanks great suggestion. the mkd3 really very crazy when added with another tools. I'll try develop the module using the mkd3, the tool is really efficient. thank's for issue

**Comment by Zaratros** [comment]
You're welcome. Good luck!

**Comment by msfcd3r** [comment]
@Zaratros  I added the function mdk3 on v0.5.8. is not activated to default.  Module >> Settings >> check the box >> mdk3 Deauth. :D thanks for suggestion.
