### ISSUE TITLE
Bad OS detection

### ISSUE THREAD

**Issue by wikijm** [P0cL4bs/3vilTwinAttacker#6]
During installation, the install.sh script don't detect correctly the OS host.
On a Raspian (Debian ARM on Raspberry Pi) the result of detection is : [+] Distribution Name: Kali
![3viltwin-attacker os detection issue](https://cloud.githubusercontent.com/assets/10724809/7294765/86bdb472-e9b0-11e4-91e1-ed76bbc912df.JPG)

**Comment by msfcd3r** [comment]
the command -> tr -s ' \011' '\012' < /etc/issue | head -n 1 , just detect  distribution ubuntu or debian. 
the script install is just to ubuntu and kali linux. but I'll fix next update for more OS. thank's.

**Comment by joridos** [comment]
```bash
$ lsb_release -d | awk '{print $2}'
Ubuntu
$ lsb_release -d | awk '{print $2}'
elementary
```
Or do with python:

```python
import platform
platform.dist()[0]
```
![](http://i.imgur.com/QM3UD1C.png)

**Comment by msfcd3r** [comment]
@wikijm please, execute the commands on Debian ARM on Raspberry Pi and show me resulted.
 root: tr -s ' \011' '\012' < /etc/issue | head -n 1
 root: lsb_release -d | awk '{print $2}'

**Comment by wikijm** [comment]
![3viltwin-attacker os detection issue](https://cloud.githubusercontent.com/assets/10724809/7304151/a00e94b0-e9f5-11e4-891e-c138947b291f.JPG)

**Comment by joridos** [comment]
You have added the Kali APT repository and upgraded your system?

I did like this before and my debian changed for kali :smile:

**Comment by wikijm** [comment]
@joridos Actually ... yes. You got me :+1:

**Comment by msfcd3r** [comment]
@wikijm  the script is correctly. it check the file on path /etc/issue. where stay the information OS. :D
