### ISSUE TITLE
Arp posion attack not working

### ISSUE THREAD

**Issue by Zaratros** [P0cL4bs/3vilTwinAttacker#7]
Hello, I couldn't get this attack to work. it shows in gateway monrouteur.home or sometimes sagem.box instead of 192.168.1.1. Here's what it says in terminal:
monrouteur.Hom1 Offline
monrouteur.Hom2 Offline
monrouteur.Hom3 Offline
monrouteur.Hom4 Offline
monrouteur.Hom5 Offline
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread
QPixmap: It is not safe to use pixmaps outside the GUI thread

**Comment by msfcd3r** [comment]
add the gateway manually on input.

**Comment by Zaratros** [comment]
I tried it before and it doesn't seem to work. I will do further testing and report it back

**Comment by msfcd3r** [comment]
Ok. your report is related  IP scan function. I'll add new update on function.

**Comment by Zaratros** [comment]
![3viltwinattacker](https://cloud.githubusercontent.com/assets/11053447/7705790/431d8b46-fe3e-11e4-8538-885f78d9228e.JPG)
As you can see, it still doesn't work even if I change the gateway.

**Comment by joridos** [comment]
The host `monrouteur.Hom1` really exist?
What is the result of `$ ping monrouteur.Hom1`

**Comment by Zaratros** [comment]
monrouteur.home exists it redirects to 192.168.1.1

**Comment by msfcd3r** [comment]
I fix error temporarily. test now.

**Comment by Zaratros** [comment]
Good job ! It works perfectly good now ! If you can add the device name next to the ip in the future it would be great :D Thank you !

**Comment by msfcd3r** [comment]
thank for issue man, I'll add
